### ISSUE TITLE
Going to overworld with a star crawler on piggy backpack crashes server

### ISSUE THREAD

**Issue by Jabber267** [IamRyan30/Decursio-Team#52] opened 2023-05-08 15:48 UTC
### Modpack Version

r1.0.4

### Launcher Used

ATLauncher

### Did this issue occur on Multiplayer, Singleplayer, or both?

Multiplayer Only, Cannot be tested in Singleplayer

### Do you, or did you had Optifine installed when the issue took place?

No

### Tried reproducing without Optifine?

No

### Describe your issue

Went to the moon to try and get a Star Crawler to create a drygmy diamond farm.
The method I decided on was to pick it up with the piggy backpack then use the /home command.
Server crashed as I started loading into the overworld.
Also tried to do the same with the Mirror trinket to go back to my spawnpoint which still resulted in the server crash.

### Log File related to your issue

https://pastebin.com/xJvePFZv

### Crash Report related to your issue

https://pastebin.com/NsxCc8EV

### Other mods

torchmaster-2.3.8
easy_villagers-1.16.5-1.0.13
ftb-ultimine-forge-1605.3.1-build.45

### Searched for known issues?

Checked Modified Features, Checked GUI & Visuals, Checked Gameplay, Searched open issues, Searched closed issues

**Comment by IamRyan30** [comment] 2023-05-08 17:50
Duplicate of https://github.com/IamRyan30/Decursio-Team/issues/37

**Closed by IamRyan30** 2023-05-08 17:50 UTC
Labels: Bug, Unreviewed
